# Generated by Django 3.2.9 on 2021-11-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplemodel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Name'),
        ),
    ]
